import { useEffect, useMemo, useState } from 'react'

export const LANGUAGES = ['id', 'en', 'ja', 'ko', 'ar', 'es', 'pt', 'fr', 'de', 'th', 'vi', 'su', 'ms', 'hi', 'zh']
export const languageNames = {
  id: 'Bahasa Indonesia', en: 'English', ja: '日本語', ko: '한국어', ar: 'العربية', es: 'Español', pt: 'Português', fr: 'Français', de: 'Deutsch', th: 'ไทย', vi: 'Tiếng Việt', su: 'Basa Sunda', ms: 'Bahasa Melayu', hi: 'हिन्दी', zh: '中文'
}
const base = {
  create: 'Create profile', viewDemo: 'View demo', explore: 'Explore', login: 'Login', register: 'Register', save: 'Save', music: 'Music', theme: 'Theme', privacy: 'Privacy', uploadMusic: 'Upload music', chooseBackground: 'Choose background', help: 'Help Center', dashboard: 'Dashboard', pricing: 'Pricing', leaderboard: 'Leaderboard', games: 'Games', account: 'Account', customize: 'Customize', links: 'Links', settings: 'Settings', analytics: 'Analytics', owner: 'Owner', language: 'Language', heroTitle: 'Build a premium profile that feels alive.', heroBody: 'TULUS is a calm blue-glass bio platform with click-to-enter, music, links, profile views, effects, games, and bekiw AI help.', start: 'Start now', openProfile: 'Open profile', flowTitle: 'Clear flow, no confusing panels.', aiTitle: 'bekiw answers like a real chat.', aiBody: 'Ask about login, dashboard, upload, music, language, views, premium, and owner panel.', languageSaved: 'Language saved', chooseLanguage: 'Choose language', publicProfile: 'Public profile', profileViews: 'Profile views', linkClicks: 'Link clicks', musicPlays: 'Music plays', completeProfile: 'Complete your profile', gameCenter: 'Game Center', dailyQuest: 'Daily quest', premiumEffects: 'Premium effects', searchHelp: 'Search guides or ask bekiw…', askBekiw: 'Ask bekiw', send: 'Send'
}
export const dictionary = {
  en: base,
  id: { ...base, create: 'Buat profile', viewDemo: 'Lihat demo', explore: 'Jelajahi', login: 'Masuk', register: 'Daftar', save: 'Simpan', music: 'Musik', theme: 'Tampilan', privacy: 'Privasi', uploadMusic: 'Upload musik', chooseBackground: 'Pilih background', help: 'Pusat Bantuan', dashboard: 'Dashboard', pricing: 'Harga', leaderboard: 'Peringkat', games: 'Game', account: 'Akun', customize: 'Edit tampilan', links: 'Link', settings: 'Pengaturan', analytics: 'Analitik', owner: 'Owner', language: 'Bahasa', heroTitle: 'Bikin profile premium yang terasa hidup.', heroBody: 'TULUS adalah platform bio blue-glass yang punya click-to-enter, musik, link, profile views, efek, game, dan AI bekiw.', start: 'Mulai sekarang', openProfile: 'Buka profile', flowTitle: 'Alurnya jelas, tanpa panel yang bikin pusing.', aiTitle: 'bekiw jawab seperti chat biasa.', aiBody: 'Tanya soal login, dashboard, upload, musik, bahasa, views, premium, dan owner panel.', languageSaved: 'Bahasa disimpan', chooseLanguage: 'Pilih bahasa', publicProfile: 'Profile publik', profileViews: 'Profile views', linkClicks: 'Klik link', musicPlays: 'Musik diputar', completeProfile: 'Lengkapi profile', gameCenter: 'Pusat Game', dailyQuest: 'Quest harian', premiumEffects: 'Efek premium', searchHelp: 'Cari panduan atau tanya bekiw…', askBekiw: 'Tanya bekiw', send: 'Kirim' },
  su: { ...base, create: 'Jieun profile', viewDemo: 'Tingali demo', explore: 'Jelajah', login: 'Asup', register: 'Daptar', save: 'Simpen', music: 'Musik', theme: 'Tampilan', help: 'Pusat Pitulung', dashboard: 'Dashboard', pricing: 'Harga', games: 'Kaulinan', account: 'Akun', customize: 'Atur tampilan', links: 'Tautan', settings: 'Setelan', language: 'Basa', heroTitle: 'Jieun profile premium anu karasa hirup.', heroBody: 'TULUS platform bio blue-glass keur profile, musik, link, views, efek, kaulinan, jeung AI bekiw.', start: 'Mimitian', openProfile: 'Buka profile', flowTitle: 'Alurna jelas, teu matak lieur.', aiTitle: 'bekiw ngajawab siga chat biasa.', searchHelp: 'Téangan pituduh atawa tanya bekiw…', send: 'Kirim' },
  ja: { ...base, create: 'プロフィール作成', viewDemo: 'デモを見る', explore: '探す', login: 'ログイン', register: '登録', save: '保存', music: '音楽', theme: 'テーマ', privacy: 'プライバシー', help: 'ヘルプセンター', dashboard: 'ダッシュボード', pricing: '料金', leaderboard: 'ランキング', games: 'ゲーム', account: 'アカウント', customize: 'カスタマイズ', links: 'リンク', settings: '設定', language: '言語', heroTitle: '生きているようなプレミアムプロフィールを作ろう。', heroBody: 'TULUS は音楽、リンク、表示数、エフェクト、ゲーム、AI bekiw を備えた青いグラス風プロフィール平台です。', start: '始める', openProfile: 'プロフィールを開く', flowTitle: '迷わない、分かりやすい流れ。', aiTitle: 'bekiw は自然なチャットのように答えます。', searchHelp: 'ガイド検索または bekiw に質問…', send: '送信' },
  ko: { ...base, create: '프로필 만들기', login: '로그인', register: '가입', save: '저장', music: '음악', theme: '테마', help: '도움말 센터', dashboard: '대시보드', pricing: '요금', leaderboard: '리더보드', games: '게임', account: '계정', customize: '꾸미기', links: '링크', settings: '설정', language: '언어', heroTitle: '살아있는 느낌의 프리미엄 프로필을 만드세요.', heroBody: 'TULUS는 음악, 링크, 조회수, 효과, 게임, bekiw AI가 있는 블루 글래스 바이오 플랫폼입니다.', start: '시작하기', openProfile: '프로필 열기', aiTitle: 'bekiw는 실제 채팅처럼 답합니다.', searchHelp: '가이드를 검색하거나 bekiw에게 질문…', send: '보내기' },
  es: { ...base, create: 'Crear perfil', login: 'Entrar', register: 'Registrarse', save: 'Guardar', music: 'Música', theme: 'Tema', help: 'Centro de ayuda', dashboard: 'Panel', pricing: 'Precios', leaderboard: 'Clasificación', games: 'Juegos', account: 'Cuenta', customize: 'Personalizar', links: 'Enlaces', settings: 'Ajustes', language: 'Idioma', heroTitle: 'Crea un perfil premium que se siente vivo.', heroBody: 'TULUS es una plataforma bio azul glass con música, enlaces, vistas, efectos, juegos y bekiw AI.', start: 'Empezar', openProfile: 'Abrir perfil', aiTitle: 'bekiw responde como un chat real.', searchHelp: 'Busca guías o pregunta a bekiw…', send: 'Enviar' },
  fr: { ...base, create: 'Créer un profil', login: 'Connexion', register: 'Inscription', save: 'Enregistrer', music: 'Musique', theme: 'Thème', help: 'Centre d’aide', dashboard: 'Tableau de bord', pricing: 'Tarifs', leaderboard: 'Classement', games: 'Jeux', account: 'Compte', customize: 'Personnaliser', links: 'Liens', settings: 'Réglages', language: 'Langue', heroTitle: 'Crée un profil premium qui semble vivant.', heroBody: 'TULUS est une plateforme bio blue glass avec musique, liens, vues, effets, jeux et bekiw AI.', start: 'Commencer', openProfile: 'Ouvrir le profil', aiTitle: 'bekiw répond comme un vrai chat.', searchHelp: 'Cherche des guides ou demande à bekiw…', send: 'Envoyer' },
  de: { ...base, create: 'Profil erstellen', login: 'Anmelden', register: 'Registrieren', save: 'Speichern', music: 'Musik', theme: 'Design', help: 'Hilfezentrum', dashboard: 'Dashboard', pricing: 'Preise', leaderboard: 'Rangliste', games: 'Spiele', account: 'Konto', customize: 'Anpassen', links: 'Links', settings: 'Einstellungen', language: 'Sprache', heroTitle: 'Erstelle ein Premium-Profil, das lebendig wirkt.', heroBody: 'TULUS ist eine Blue-Glass-Bio-Plattform mit Musik, Links, Views, Effekten, Spielen und bekiw AI.', start: 'Starten', openProfile: 'Profil öffnen', aiTitle: 'bekiw antwortet wie ein echter Chat.', searchHelp: 'Guides suchen oder bekiw fragen…', send: 'Senden' },
  pt: { ...base, create: 'Criar perfil', login: 'Entrar', register: 'Cadastrar', save: 'Salvar', music: 'Música', theme: 'Tema', help: 'Central de ajuda', dashboard: 'Painel', pricing: 'Preços', leaderboard: 'Ranking', games: 'Jogos', account: 'Conta', customize: 'Personalizar', links: 'Links', settings: 'Configurações', language: 'Idioma', heroTitle: 'Crie um perfil premium que parece vivo.', heroBody: 'TULUS é uma plataforma bio blue glass com música, links, views, efeitos, jogos e bekiw AI.', start: 'Começar', openProfile: 'Abrir perfil', aiTitle: 'bekiw responde como um chat real.', searchHelp: 'Pesquise guias ou pergunte ao bekiw…', send: 'Enviar' },
  ar: { ...base, create: 'إنشاء ملف', login: 'دخول', register: 'تسجيل', save: 'حفظ', music: 'موسيقى', theme: 'المظهر', help: 'مركز المساعدة', dashboard: 'لوحة التحكم', pricing: 'الأسعار', leaderboard: 'الترتيب', games: 'الألعاب', account: 'الحساب', customize: 'تخصيص', links: 'روابط', settings: 'الإعدادات', language: 'اللغة', heroTitle: 'اصنع ملفًا شخصيًا فاخرًا يبدو حيًا.', heroBody: 'TULUS منصة سيرة زجاجية زرقاء مع موسيقى وروابط ومشاهدات ومؤثرات وألعاب و AI bekiw.', start: 'ابدأ', openProfile: 'افتح الملف', aiTitle: 'bekiw يجيب مثل محادثة حقيقية.', searchHelp: 'ابحث في الأدلة أو اسأل bekiw…', send: 'إرسال' },
  vi: { ...base, create: 'Tạo hồ sơ', viewDemo: 'Xem demo', explore: 'Khám phá', login: 'Đăng nhập', register: 'Đăng ký', save: 'Lưu', music: 'Nhạc', theme: 'Giao diện', privacy: 'Quyền riêng tư', uploadMusic: 'Tải nhạc lên', chooseBackground: 'Chọn nền', help: 'Trung tâm trợ giúp', dashboard: 'Bảng điều khiển', pricing: 'Bảng giá', leaderboard: 'Bảng xếp hạng', games: 'Trò chơi', account: 'Tài khoản', customize: 'Tùy chỉnh', links: 'Liên kết', settings: 'Cài đặt', analytics: 'Phân tích', owner: 'Chủ sở hữu', language: 'Ngôn ngữ', heroTitle: 'Tạo một hồ sơ cao cấp có cảm giác sống động.', heroBody: 'TULUS là nền tảng bio blue glass với click-to-enter, nhạc, liên kết, lượt xem, hiệu ứng, game và AI bekiw.', start: 'Bắt đầu', openProfile: 'Mở hồ sơ', flowTitle: 'Luồng rõ ràng, không rối.', aiTitle: 'bekiw trả lời như một cuộc trò chuyện thật.', aiBody: 'Hỏi về đăng nhập, dashboard, upload, nhạc, ngôn ngữ, views, premium và owner panel.', languageSaved: 'Đã lưu ngôn ngữ', chooseLanguage: 'Chọn ngôn ngữ', publicProfile: 'Hồ sơ công khai', profileViews: 'Lượt xem hồ sơ', linkClicks: 'Lượt nhấp liên kết', musicPlays: 'Lượt phát nhạc', completeProfile: 'Hoàn thiện hồ sơ', gameCenter: 'Trung tâm trò chơi', dailyQuest: 'Thử thách hằng ngày', premiumEffects: 'Hiệu ứng cao cấp', searchHelp: 'Tìm hướng dẫn hoặc hỏi bekiw…', askBekiw: 'Hỏi bekiw', send: 'Gửi' },
  hi: { ...base, create: 'प्रोफाइल बनाएं', login: 'लॉग इन', register: 'रजिस्टर', save: 'सेव', music: 'संगीत', theme: 'थीम', help: 'सहायता केंद्र', dashboard: 'डैशबोर्ड', pricing: 'कीमत', leaderboard: 'लीडरबोर्ड', games: 'गेम्स', account: 'अकाउंट', customize: 'कस्टमाइज़', links: 'लिंक', settings: 'सेटिंग्स', language: 'भाषा', heroTitle: 'एक प्रीमियम प्रोफाइल बनाएं जो जीवंत लगे।', start: 'शुरू करें', openProfile: 'प्रोफाइल खोलें', send: 'भेजें' },
  zh: { ...base, create: '创建主页', login: '登录', register: '注册', save: '保存', music: '音乐', theme: '主题', help: '帮助中心', dashboard: '仪表盘', pricing: '价格', leaderboard: '排行榜', games: '游戏', account: '账号', customize: '自定义', links: '链接', settings: '设置', language: '语言', heroTitle: '打造有生命感的高级个人主页。', start: '开始', openProfile: '打开主页', send: '发送' },
  ms: { ...base, create: 'Buat profil', login: 'Log masuk', register: 'Daftar', save: 'Simpan', music: 'Muzik', theme: 'Tema', help: 'Pusat bantuan', dashboard: 'Dashboard', pricing: 'Harga', leaderboard: 'Kedudukan', games: 'Permainan', account: 'Akaun', customize: 'Ubah suai', links: 'Pautan', settings: 'Tetapan', language: 'Bahasa', heroTitle: 'Bina profil premium yang terasa hidup.', start: 'Mula', openProfile: 'Buka profil', send: 'Hantar' },
  th: { ...base, create: 'สร้างโปรไฟล์', login: 'เข้าสู่ระบบ', register: 'สมัคร', save: 'บันทึก', music: 'เพลง', theme: 'ธีม', help: 'ศูนย์ช่วยเหลือ', dashboard: 'แดชบอร์ด', pricing: 'ราคา', leaderboard: 'อันดับ', games: 'เกม', account: 'บัญชี', customize: 'ปรับแต่ง', links: 'ลิงก์', settings: 'ตั้งค่า', language: 'ภาษา', heroTitle: 'สร้างโปรไฟล์พรีเมียมที่มีชีวิตชีวา', start: 'เริ่ม', openProfile: 'เปิดโปรไฟล์', send: 'ส่ง' }
}

export function normalizeLang(lang = 'id') { return LANGUAGES.includes(lang) ? lang : 'en' }
export function t(lang = 'id', key = '') { const code = normalizeLang(lang); return dictionary[code]?.[key] || dictionary.en[key] || key }
export function getInitialLang() { return normalizeLang(localStorage.getItem('tulus.lang') || (navigator.language || 'id').slice(0,2) || 'id') }
export function nextLang(lang = 'id') { const idx = LANGUAGES.indexOf(normalizeLang(lang)); return LANGUAGES[(idx + 1) % LANGUAGES.length] }
export function setGlobalLang(code) { const lang = normalizeLang(code); localStorage.setItem('tulus.lang', lang); document.documentElement.lang = lang; document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'; window.dispatchEvent(new CustomEvent('tulus-language-change', { detail: lang })); return lang }

export function getText(key = '', lang = getInitialLang()) { return t(lang, key) }
export function setLanguage(code) { return setGlobalLang(code) }
export function useTulusLanguage() {
  const [lang, setLangState] = useState(getInitialLang())
  useEffect(() => {
    const onLang = (event) => setLangState(normalizeLang(event.detail || localStorage.getItem('tulus.lang')))
    window.addEventListener('tulus-language-change', onLang)
    window.addEventListener('storage', onLang)
    document.documentElement.lang = lang
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
    return () => { window.removeEventListener('tulus-language-change', onLang); window.removeEventListener('storage', onLang) }
  }, [lang])
  const setLang = (code) => setLangState(setGlobalLang(code))
  const tr = useMemo(() => (key) => t(lang, key), [lang])
  return { lang, setLang, t: tr, name: languageNames[lang] || languageNames.en }
}
