import { useEffect, useMemo, useState } from 'react'

export const LANGUAGES = ['id', 'en', 'ja', 'ko', 'ar', 'es', 'pt', 'fr', 'de', 'th', 'vi']
export const languageNames = { id: 'Bahasa Indonesia', en: 'English', ja: '日本語', ko: '한국어', ar: 'العربية', es: 'Español', pt: 'Português', fr: 'Français', de: 'Deutsch', th: 'ไทย', vi: 'Tiếng Việt' }

const base = {
  brand: 'TULUS', tagline: 'A quiet profile space.', create: 'Create profile', viewDemo: 'View demo', explore: 'Explore', login: 'Login', register: 'Register', logout: 'Logout', save: 'Save', saved: 'Saved', publish: 'Publish', unpublish: 'Unpublish', cancel: 'Cancel', clear: 'Clear', copy: 'Copy', search: 'Search', upload: 'Upload', reset: 'Reset', edit: 'Edit', preview: 'Preview', next: 'Next', back: 'Back', open: 'Open', close: 'Close', start: 'Start now', send: 'Send', music: 'Music', theme: 'Theme', privacy: 'Privacy', uploadMusic: 'Upload music', chooseBackground: 'Choose background', uploadAvatar: 'Upload avatar', addGallery: 'Add gallery photo', help: 'Help Center', dashboard: 'Dashboard', pricing: 'Pricing', leaderboard: 'Leaderboard', games: 'Games', account: 'Account', customize: 'Customize', links: 'Links', settings: 'Settings', analytics: 'Analytics', badges: 'Badges', billing: 'Billing', owner: 'Owner', language: 'Language', heroTitle: 'Build a premium profile that feels alive.', heroBody: 'TULUS is a calm blue-glass bio platform with click-to-enter, music, links, profile views, effects, games, and bekiw AI help.', openProfile: 'Open profile', flowTitle: 'Clear flow, no confusing panels.', aiTitle: 'bekiw answers like a real chat.', aiBody: 'Ask about login, dashboard, upload, music, language, views, premium, and owner panel.', languageSaved: 'Language saved', chooseLanguage: 'Choose language', publicProfile: 'Public profile', profileViews: 'Profile views', linkClicks: 'Link clicks', musicPlays: 'Music plays', completeProfile: 'Complete your profile', gameCenter: 'Game Center', dailyQuest: 'Daily quest', premiumEffects: 'Premium effects', searchHelp: 'Search guides or ask bekiw…', askBekiw: 'Ask bekiw', overview: 'Overview', profile: 'Profile', uploadLabel: 'Upload', themes: 'Themes', effects: 'Effects', cursor: 'Cursor', premium: 'Premium', safety: 'Safety', troubleshooting: 'Troubleshooting', gettingStarted: 'Getting Started', popularQuestions: 'Popular questions', quickFixes: 'Quick fixes', stillNeedHelp: 'Still need help?', emptyTitle: 'Nothing here yet', emptyBody: 'Add data first and this area will become useful.', errorGeneric: 'Something went wrong. Try again or check setup.', notFound: 'Page not found', publicProfileLabel: 'Public profile', privateProfile: 'Private profile', viewCounter: 'Views', planFree: 'Free', planPlus: 'Plus', planPro: 'Pro', planLifetime: 'Lifetime', ownerPanel: 'Owner panel', statusOnline: 'online', thinking: 'bekiw is thinking…', messageBekiw: 'Message bekiw…', quickQuestionBackground: 'How do I change background?', quickQuestionDiscord: 'How do I add Discord link?', quickQuestionMusic: 'Why does YouTube not autoplay?', quickQuestionMp3: 'How do I use MP3 music?', quickQuestionLanguage: 'How do I change language?'
}

const overrides = {
  id: { create: 'Buat profile', viewDemo: 'Lihat demo', explore: 'Jelajahi', login: 'Masuk', register: 'Daftar', logout: 'Keluar', save: 'Simpan', saved: 'Tersimpan', publish: 'Publikasikan', unpublish: 'Sembunyikan', cancel: 'Batal', clear: 'Bersihkan', copy: 'Salin', search: 'Cari', upload: 'Upload', reset: 'Reset', edit: 'Edit', preview: 'Preview', next: 'Lanjut', back: 'Kembali', open: 'Buka', close: 'Tutup', start: 'Mulai sekarang', send: 'Kirim', music: 'Musik', theme: 'Tampilan', privacy: 'Privasi', uploadMusic: 'Upload musik', chooseBackground: 'Pilih background', uploadAvatar: 'Upload avatar', addGallery: 'Tambah foto galeri', help: 'Pusat Bantuan', dashboard: 'Dashboard', pricing: 'Harga', leaderboard: 'Peringkat', games: 'Game', account: 'Akun', customize: 'Edit tampilan', links: 'Link', settings: 'Pengaturan', analytics: 'Analitik', badges: 'Badge', billing: 'Billing', owner: 'Owner', language: 'Bahasa', heroTitle: 'Bikin profile premium yang terasa hidup.', heroBody: 'TULUS adalah platform bio blue-glass yang punya click-to-enter, musik, link, profile views, efek, game, dan AI bekiw.', openProfile: 'Buka profile', flowTitle: 'Alurnya jelas, tanpa panel yang bikin pusing.', aiTitle: 'bekiw jawab seperti chat biasa.', aiBody: 'Tanya soal login, dashboard, upload, musik, bahasa, views, premium, dan owner panel.', languageSaved: 'Bahasa disimpan', chooseLanguage: 'Pilih bahasa', publicProfile: 'Profile publik', profileViews: 'Profile views', linkClicks: 'Klik link', musicPlays: 'Musik diputar', completeProfile: 'Lengkapi profile', gameCenter: 'Pusat Game', dailyQuest: 'Quest harian', premiumEffects: 'Efek premium', searchHelp: 'Cari panduan atau tanya bekiw…', askBekiw: 'Tanya bekiw', overview: 'Ringkasan', profile: 'Profile', uploadLabel: 'Upload', themes: 'Tema', effects: 'Efek', cursor: 'Kursor', premium: 'Premium', safety: 'Keamanan', troubleshooting: 'Troubleshooting', gettingStarted: 'Mulai', popularQuestions: 'Pertanyaan populer', quickFixes: 'Perbaikan cepat', stillNeedHelp: 'Masih butuh bantuan?', emptyTitle: 'Belum ada data', emptyBody: 'Tambahkan data dulu, nanti bagian ini otomatis terisi.', errorGeneric: 'Ada yang error. Coba lagi atau cek setup.', notFound: 'Halaman tidak ditemukan', publicProfileLabel: 'Profile publik', privateProfile: 'Profile privat', viewCounter: 'Views', ownerPanel: 'Panel owner', statusOnline: 'online', thinking: 'bekiw sedang mengetik…', messageBekiw: 'Chat bekiw…', quickQuestionBackground: 'Cara ubah background?', quickQuestionDiscord: 'Cara tambah link Discord?', quickQuestionMusic: 'Kenapa YouTube tidak autoplay?', quickQuestionMp3: 'Cara pakai musik MP3?', quickQuestionLanguage: 'Cara ganti bahasa?' },
  ja: { login: 'ログイン', register: '登録', save: '保存', search: '検索', send: '送信', help: 'ヘルプセンター', dashboard: 'ダッシュボード', pricing: '料金', leaderboard: 'ランキング', games: 'ゲーム', account: 'アカウント', customize: 'カスタマイズ', links: 'リンク', settings: '設定', language: '言語', heroTitle: '生きているようなプレミアムプロフィールを作ろう。', heroBody: 'TULUS は音楽、リンク、表示数、エフェクト、ゲーム、AI bekiw を備えた青いグラス風プロフィール平台です。', start: '始める', openProfile: 'プロフィールを開く', aiTitle: 'bekiw は自然なチャットのように答えます。', searchHelp: 'ガイド検索または bekiw に質問…', messageBekiw: 'bekiw にメッセージ…' },
  ko: { login: '로그인', register: '가입', save: '저장', search: '검색', send: '보내기', help: '도움말 센터', dashboard: '대시보드', pricing: '요금', leaderboard: '리더보드', games: '게임', account: '계정', customize: '꾸미기', links: '링크', settings: '설정', language: '언어', heroTitle: '살아있는 느낌의 프리미엄 프로필을 만드세요.', start: '시작하기', openProfile: '프로필 열기', aiTitle: 'bekiw는 실제 채팅처럼 답합니다.', searchHelp: '가이드를 검색하거나 bekiw에게 질문…', messageBekiw: 'bekiw에게 메시지…' },
  ar: { login: 'دخول', register: 'تسجيل', save: 'حفظ', search: 'بحث', send: 'إرسال', help: 'مركز المساعدة', dashboard: 'لوحة التحكم', pricing: 'الأسعار', leaderboard: 'الترتيب', games: 'الألعاب', account: 'الحساب', customize: 'تخصيص', links: 'روابط', settings: 'الإعدادات', language: 'اللغة', heroTitle: 'اصنع ملفًا شخصيًا فاخرًا يبدو حيًا.', start: 'ابدأ', openProfile: 'افتح الملف', aiTitle: 'bekiw يجيب مثل محادثة حقيقية.', searchHelp: 'ابحث في الأدلة أو اسأل bekiw…', messageBekiw: 'راسل bekiw…' },
  es: { login: 'Entrar', register: 'Registrarse', save: 'Guardar', search: 'Buscar', send: 'Enviar', help: 'Centro de ayuda', dashboard: 'Panel', pricing: 'Precios', leaderboard: 'Clasificación', games: 'Juegos', account: 'Cuenta', customize: 'Personalizar', links: 'Enlaces', settings: 'Ajustes', language: 'Idioma', heroTitle: 'Crea un perfil premium que se siente vivo.', start: 'Empezar', openProfile: 'Abrir perfil', aiTitle: 'bekiw responde como un chat real.', searchHelp: 'Busca guías o pregunta a bekiw…', messageBekiw: 'Mensaje a bekiw…' },
  pt: { login: 'Entrar', register: 'Cadastrar', save: 'Salvar', search: 'Buscar', send: 'Enviar', help: 'Central de ajuda', dashboard: 'Painel', pricing: 'Preços', leaderboard: 'Ranking', games: 'Jogos', account: 'Conta', customize: 'Personalizar', links: 'Links', settings: 'Configurações', language: 'Idioma', heroTitle: 'Crie um perfil premium que parece vivo.', start: 'Começar', openProfile: 'Abrir perfil', aiTitle: 'bekiw responde como um chat real.', searchHelp: 'Pesquise guias ou pergunte ao bekiw…', messageBekiw: 'Mensagem para bekiw…' },
  fr: { login: 'Connexion', register: 'Inscription', save: 'Enregistrer', search: 'Chercher', send: 'Envoyer', help: 'Centre d’aide', dashboard: 'Tableau de bord', pricing: 'Tarifs', leaderboard: 'Classement', games: 'Jeux', account: 'Compte', customize: 'Personnaliser', links: 'Liens', settings: 'Réglages', language: 'Langue', heroTitle: 'Crée un profil premium qui semble vivant.', start: 'Commencer', openProfile: 'Ouvrir le profil', aiTitle: 'bekiw répond comme un vrai chat.', searchHelp: 'Cherche des guides ou demande à bekiw…', messageBekiw: 'Message à bekiw…' },
  de: { login: 'Anmelden', register: 'Registrieren', save: 'Speichern', search: 'Suchen', send: 'Senden', help: 'Hilfezentrum', dashboard: 'Dashboard', pricing: 'Preise', leaderboard: 'Rangliste', games: 'Spiele', account: 'Konto', customize: 'Anpassen', links: 'Links', settings: 'Einstellungen', language: 'Sprache', heroTitle: 'Erstelle ein Premium-Profil, das lebendig wirkt.', start: 'Starten', openProfile: 'Profil öffnen', aiTitle: 'bekiw antwortet wie ein echter Chat.', searchHelp: 'Guides suchen oder bekiw fragen…', messageBekiw: 'bekiw schreiben…' },
  th: { login: 'เข้าสู่ระบบ', register: 'สมัคร', save: 'บันทึก', search: 'ค้นหา', send: 'ส่ง', help: 'ศูนย์ช่วยเหลือ', dashboard: 'แดชบอร์ด', pricing: 'ราคา', leaderboard: 'อันดับ', games: 'เกม', account: 'บัญชี', customize: 'ปรับแต่ง', links: 'ลิงก์', settings: 'ตั้งค่า', language: 'ภาษา', heroTitle: 'สร้างโปรไฟล์พรีเมียมที่มีชีวิตชีวา', start: 'เริ่ม', openProfile: 'เปิดโปรไฟล์', aiTitle: 'bekiw ตอบเหมือนแชทจริง', searchHelp: 'ค้นหาคู่มือหรือถาม bekiw…', messageBekiw: 'ส่งข้อความถึง bekiw…' },
  vi: { login: 'Đăng nhập', register: 'Đăng ký', save: 'Lưu', search: 'Tìm kiếm', send: 'Gửi', help: 'Trung tâm trợ giúp', dashboard: 'Bảng điều khiển', pricing: 'Bảng giá', leaderboard: 'Bảng xếp hạng', games: 'Trò chơi', account: 'Tài khoản', customize: 'Tùy chỉnh', links: 'Liên kết', settings: 'Cài đặt', language: 'Ngôn ngữ', heroTitle: 'Tạo một hồ sơ cao cấp có cảm giác sống động.', heroBody: 'TULUS là nền tảng bio blue glass với click-to-enter, nhạc, liên kết, lượt xem, hiệu ứng, game và AI bekiw.', start: 'Bắt đầu', openProfile: 'Mở hồ sơ', aiTitle: 'bekiw trả lời như một cuộc trò chuyện thật.', searchHelp: 'Tìm hướng dẫn hoặc hỏi bekiw…', messageBekiw: 'Nhắn cho bekiw…' }
}

export const dictionary = Object.fromEntries(LANGUAGES.map((lang) => [lang, { ...base, ...(overrides[lang] || {}) }]))

export function normalizeLang(lang = 'id') { return LANGUAGES.includes(String(lang).slice(0,2)) ? String(lang).slice(0,2) : 'en' }
export function t(lang = 'id', key = '') { const code = normalizeLang(lang); return dictionary[code]?.[key] || dictionary.en[key] || key }
export function getInitialLang() { return normalizeLang(localStorage.getItem('tulus.lang') || (navigator.language || 'id').slice(0,2) || 'id') }
export function nextLang(lang = 'id') { const idx = LANGUAGES.indexOf(normalizeLang(lang)); return LANGUAGES[(idx + 1) % LANGUAGES.length] }
export function setGlobalLang(code) { const lang = normalizeLang(code); localStorage.setItem('tulus.lang', lang); document.documentElement.lang = lang; document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'; window.dispatchEvent(new CustomEvent('tulus-language-change', { detail: lang })); return lang }
export function getText(key = '', lang = getInitialLang()) { return t(lang, key) }
export function setLanguage(code) { return setGlobalLang(code) }
export function useTulusLanguage() {
  const [lang, setLangState] = useState(getInitialLang())
  useEffect(() => {
    const onLang = (event) => setLangState(normalizeLang(event.detail || localStorage.getItem('tulus.lang')))
    window.addEventListener('tulus-language-change', onLang)
    window.addEventListener('storage', onLang)
    document.documentElement.lang = lang
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
    return () => { window.removeEventListener('tulus-language-change', onLang); window.removeEventListener('storage', onLang) }
  }, [lang])
  const setLang = (code) => setLangState(setGlobalLang(code))
  const tr = useMemo(() => (key) => t(lang, key), [lang])
  return { lang, setLang, t: tr, name: languageNames[lang] || languageNames.en }
}
