import V7DashboardShell from '../components/V7DashboardShell.jsx'
import BekiwAIChat from '../components/BekiwAIChat.jsx'
import { useTulusLanguage } from '../lib/i18n.js'

export default function AccountDashboard({ user, profile }) {
  const { t } = useTulusLanguage()
  const checklist = ['Upload avatar', 'Add description', 'Add socials', 'Choose background', 'Pick music', 'Set language', 'Try Game Center', 'Check analytics']
  return <V7DashboardShell user={user} profile={profile} active="Overview"><div className="v100-dash-head million-dash-head"><div><p className="v100-kicker">{t('account')}</p><h1>Overview</h1><p>Everything important is grouped here: identity, views, completion, games, AI helper, and shortcuts.</p></div><a className="v100-primary" href={`/${profile?.username || 'bekiw'}`}>{t('openProfile')}</a></div><section className="v100-overview-grid million-overview-grid"><article><small>Username</small><b>{profile?.username || 'bekiw'}</b><span>public URL active</span></article><article><small>Plan</small><b>{profile?.plan || 'Free'}</b><span>upgrade anytime</span></article><article><small>Score</small><b>8,240</b><span>games + profile</span></article><article><small>{t('profileViews')}</small><b>{profile?.views || 0}</b><span>visible if enabled</span></article></section><section className="v100-completion million-completion"><div><h2>{t('completeProfile')}</h2><p>Keep it simple: avatar, description, links, background, music, language, and effects.</p></div><div className="v100-checks">{checklist.map((x, i) => <a href={i===6?'/games':'/customize'} key={x} className={i < 4 ? 'done' : ''}>◆ {x}</a>)}</div></section><section className="v100-dashboard-grid million-dashboard-grid"><article className="v100-panel"><h2>Views this week</h2><div className="v100-line-chart"><em/><em/><em/><em/><em/><em/><em/></div></article><article className="v100-panel"><h2>{t('gameCenter')}</h2><p>Focus Tap, Memory Light, Aura Match, and Word Flow are ready for quick engagement.</p><a className="v100-secondary" href="/games">Open games</a></article><article className="v100-panel"><h2>bekiw AI shortcut</h2><BekiwAIChat compact /></article></section></V7DashboardShell>
}
