import V7DashboardShell from '../components/V7DashboardShell.jsx'
import LanguageSwitcher from '../components/LanguageSwitcher.jsx'
import BrandIcon from '../components/BrandIcon.jsx'
import { useTulusLanguage } from '../lib/i18n.js'

export default function AccountSettings({ user, profile }) {
  const { t, name } = useTulusLanguage()
  return <V7DashboardShell user={user} profile={profile} active="Settings"><section className="v500-settings million-settings"><p className="v100-kicker">{t('settings')}</p><h1>Control your account without confusion.</h1><p>Identity, language, connections, security, notifications, privacy, and device preferences are grouped clearly.</p><div className="v500-settings-grid million-settings-grid"><article><h2>General</h2><label>Username<input defaultValue={profile?.username || 'bekiw'} /></label><label>Display name<input defaultValue={profile?.display_name || 'bekiw'} /></label><label>Email<input defaultValue={user?.email || 'baehaqieqi07@gmail.com'} /></label><button>{t('save')}</button></article><article><h2>{t('language')}</h2><p>Current language: <b>{name}</b>. Changing this updates landing, nav, dashboard labels, help center, and bekiw chat copy.</p><LanguageSwitcher /></article><article><h2>Connections</h2><button><BrandIcon name="google"/> Connect Google</button><button><BrandIcon name="discord"/> Connect Discord</button><button><BrandIcon name="spotify"/> Connect Spotify</button></article><article><h2>Security</h2><label><input type="checkbox" defaultChecked/> Turnstile on sensitive actions</label><label><input type="checkbox"/> Email login alerts</label><label><input type="checkbox" defaultChecked/> Hide owner routes from public UI</label><button>Change password</button></article><article><h2>Notifications</h2><label><input type="checkbox" defaultChecked/> New view summary</label><label><input type="checkbox" defaultChecked/> Link click summary</label><label><input type="checkbox"/> Premium update news</label></article><article className="danger"><h2>Danger zone</h2><button>Disable account</button><button>Delete account</button></article></div></section></V7DashboardShell>
}
