import { useMemo, useState } from 'react'
import OwnerGuard from '../components/OwnerGuard.jsx'
import TurnstileBox from '../components/TurnstileBox.jsx'
import BekiwAIChat from '../components/BekiwAIChat.jsx'
import { musicRecommendations as builtInMusic } from '../data/musicRecommendations.js'

export default function OwnerPanel({ user, profile, setProfile, payments = [], setPayments = () => {}, musicRecommendations = [], setMusicRecommendations }) {
  const [token, setToken] = useState('')
  const [logs, setLogs] = useState([])
  const [musicForm, setMusicForm] = useState({ title: '', artist: '', mood: 'calm', category: 'Calm', audio_url: '', cover_url: '', is_premium: false, is_active: true })
  const managedMusic = musicRecommendations.length ? musicRecommendations : builtInMusic
  const stats = useMemo(() => ({ users: 1, profiles: 1, public: profile.visibility === 'public' ? 1 : 0, payments: payments.length, reports: 1, music: managedMusic.length, premium: profile.plan === 'premium' ? 1 : 0, logs: logs.length }), [profile, payments.length, managedMusic.length, logs.length])
  const log = (action) => setLogs((prev) => [{ action, created_at: new Date().toISOString(), actor: user?.email || 'owner' }, ...prev])
  const addMusic = () => { if (!token || !musicForm.title) return; setMusicRecommendations?.((prev) => [{ ...musicForm, id: crypto.randomUUID(), sort_order: prev.length + 1 }, ...prev]); setMusicForm({ title: '', artist: '', mood: 'calm', category: 'Calm', audio_url: '', cover_url: '', is_premium: false, is_active: true }); log('create_music_recommendation') }
  return <OwnerGuard user={user}><main className="v100-owner"><section className="v100-owner-head"><div><p className="v100-kicker">TULUS Control</p><h1>Owner dashboard</h1><p>Users, profiles, payments, reports, recommended music, AI help, settings, and logs in one clean internal place.</p></div><a className="v100-secondary" href="/account">Back to account</a></section><TurnstileBox required onToken={setToken} /><section className="v100-owner-stats">{Object.entries(stats).map(([k,v])=><article key={k}><small>{k}</small><b>{v}</b></article>)}</section><section className="v100-owner-grid"><article><h2>User & Profile Control</h2><input placeholder="Search email or username"/><div className="v100-stack"><b>@{profile.username}</b><span>{profile.visibility}</span><button onClick={() => { setProfile((p)=>({...p,is_suspended:!p.is_suspended})); log('toggle_suspend') }}>{profile.is_suspended ? 'Unsuspend' : 'Suspend'}</button><button onClick={() => { setProfile((p)=>({...p,is_hidden_from_explore:!p.is_hidden_from_explore})); log('toggle_explore') }}>Hide Explore</button></div></article><article><h2>Platform Settings</h2>{['Maintenance mode','Owner actions require Turnstile','AI support enabled','Public explore enabled'].map((x,i)=><label key={x}><input type="checkbox" defaultChecked={i>0}/> {x}</label>)}</article><article><h2>Recommended Music</h2><input placeholder="Title" value={musicForm.title} onChange={(e)=>setMusicForm({...musicForm,title:e.target.value})}/><input placeholder="Artist" value={musicForm.artist} onChange={(e)=>setMusicForm({...musicForm,artist:e.target.value})}/><input placeholder="Audio URL" value={musicForm.audio_url} onChange={(e)=>setMusicForm({...musicForm,audio_url:e.target.value})}/><button onClick={addMusic}>Add Music</button><div className="v100-mini-list">{managedMusic.slice(0,5).map((m)=><p key={m.id}><b>{m.title}</b><span>{m.category}</span></p>)}</div></article><article><h2>bekiw AI Control</h2><BekiwAIChat compact /></article><article><h2>Reports</h2><div className="v100-stack"><b>demo report</b><span>pending review</span><button onClick={()=>log('review_report')}>Review</button></div></article><article><h2>Activity Logs</h2>{logs.length ? logs.map((x,i)=><p key={i}><b>{x.action}</b><small>{new Date(x.created_at).toLocaleString()}</small></p>) : <p>No owner actions yet.</p>}</article></section></main></OwnerGuard>
}
